# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-10 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 17, 27, 23, 246236)),
        ),
    ]
