# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0002_employees_mydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('Idx', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=200)),
                ('Full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Blog', models.CharField(blank=True, max_length=200, null=True)),
                ('Public_repos', models.PositiveIntegerField()),
                ('Public_gists', models.PositiveIntegerField()),
                ('Email', models.CharField(blank=True, max_length=250, null=True)),
                ('Followers', models.PositiveIntegerField()),
                ('Following', models.PositiveIntegerField()),
                ('Updated_on', models.DateField()),
                ('Image', models.CharField(default='No Picture Available. Weird!', max_length=500)),
            ],
            options={
                'verbose_name': '1_User Data',
                'verbose_name_plural': '1_User Data',
            },
        ),
        migrations.DeleteModel(
            name='employees',
        ),
        migrations.CreateModel(
            name='ReportMonth',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('userdetail.user_data',),
        ),
        migrations.CreateModel(
            name='ReportToday',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('userdetail.user_data',),
        ),
        migrations.CreateModel(
            name='ReportYear',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('userdetail.user_data',),
        ),
    ]
